trigger:
  branches:
    include:
      - main # Adjust the branch as needed

variables:
  dockerRegistryServiceConnection: 'landit-dev-docker-sc' # Replace with your Docker Registry Service Connection name
  containerRegistry: 'landitreceevi.azurecr.io' # Replace with your ACR name
  imageName: 'landit-receevi-nextjs'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # Checkout the code
          - task: Checkout@1

          # Download the .env file from Azure DevOps secure files
          - task: DownloadSecureFile@1
            name: envFile
            inputs:
              secureFile: '<YourSecureEnvFileName>' # Replace with your secure file name

          # Install dependencies and build the Next.js app
          - script: |
              mv $(envFile.secureFilePath) .env
              npm install
              npm run build
            displayName: 'Install and Build Next.js App'

          # Build the Docker image
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              dockerfile: 'Dockerfile'
              tags: |
                $(containerRegistry)/$(imageName):$(Build.BuildId)
                $(containerRegistry)/$(imageName):latest

          # Push the Docker image to Azure Container Registry
          - task: Docker@2
            displayName: 'Push Docker Image'
            inputs:
              command: 'push'
              tags: |
                $(containerRegistry)/$(imageName):$(Build.BuildId)
                $(containerRegistry)/$(imageName):latest
